name: main branch autotests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile latest verilogtree source
        run: make
      - name: invoke Python test
        run: python3 tests/verilogtree-tests.py
